### PR TITLE
fix navbar not closing down when clicking outside of it

### PR DESCRIPTION
**Pull request by abitsalihu**
Fixed the navbar bug, by adding the min-height of the "content section" part to 100vh, and if there is more content inside the "content section" the "vh" will just increase itself.

### CODE REVIEW

**Comment by rg-wood** [comment]
@abitsalihu Fantastic, thanks for this! I'll cut a release now.

**Comment by rg-wood** [comment]
Fixes https://github.com/grislyeye/three-meet/issues/95

**Comment by rg-wood** [comment]
Released as part of https://github.com/grislyeye/three-meet/releases/tag/v0.18.1

**Comment by abitsalihu** [comment]
@rg-wood no problem, glad I could help.
Feel free to message if you need help with anything else, whenever u wanna make the page responsive feel free to msg me.
I followed you as well :)

**Comment by rgladwell** [comment]
@abitsalihu If you're happy to do the work of making the site responsive that would be fantastic. I can assign it to you now?

**Comment by rg-wood** [comment]
@abitsalihu If you're happy to do the work of making the site responsive that would be fantastic. I can assign it to you now?

**Comment by abitsalihu** [comment]
@rg-wood yeah sure, I will tackle it tomorrow, I will also open some [enhancement] issues, that maybe how the nav would look better full screen when in mobile mode but I will open the issues after I finish the media queries, and will provide some screenshots on how I think that should look like!

**Comment by rg-wood** [comment]
@abitsalihu fantastic, thank you!

**Pull request merged**
